[package]
name = "lemon_dos"
version = "0.1.0"
edition = "2021"

[dependencies]
x86_64 = "0.14.10"
bootloader = "0.9.23"
uart_16550 = "0.2.18"
spin = "0.9.5"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]